const navItems=[['home','Today','◉'],['calendar','Calendar','□'],['diary','Diary','✎'],['insights','Insights','✦'],['profile','Profile','○']];
const state={priority:'Medium',tasks:JSON.parse(localStorage.getItem('cosmic.tasks')||'null')||[
{time:'08:30',title:'Morning planning',category:'Personal',luck:76,status:'completed'},
{time:'10:00',title:'Project deep work',category:'Work',luck:88,status:'planned'},
{time:'14:30',title:'Review financial plan',category:'Finance',luck:91,status:'planned'},
{time:'17:40',title:'Walk & reset',category:'Wellness',luck:73,status:'planned'}]};
const today=new Date(2026,7,28);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function navHTML(){return navItems.map(([id,label,icon])=>`<button class="nav-btn ${id==='home'?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}
$('#desktopNav').innerHTML=navHTML(); $('#mobileNav').innerHTML=navHTML();
function setPage(page){$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const labels={home:['Friday · 28 August','Today'],calendar:['Plan with context','Calendar'],diary:['Private by design','Diary'],insights:['Your personal synthesis','Insights'],profile:['Account & preferences','Profile']};$('#pageEyebrow').textContent=labels[page][0];$('#pageTitle').textContent=labels[page][1];window.scrollTo({top:0,behavior:'smooth'});$('#mainContent').focus({preventScroll:true})}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-page]');if(btn)setPage(btn.dataset.page)});
function taskList(){return state.tasks.sort((a,b)=>a.time.localeCompare(b.time)).map(t=>`<div class="timeline-item ${t.status==='completed'?'completed':''}"><div class="time">${t.time}</div><div class="rail"><span class="dot"></span></div><div class="task-body"><strong>${escapeHtml(t.title)}</strong><small>${t.status==='completed'?'Completed':'Planned'} · ${t.category}</small><div class="task-meta"><span class="tag ${t.luck>=85?'good':'accent'}">${t.luck}% alignment</span><span class="tag">${t.category}</span></div></div></div>`).join('')}
function renderHome(){ $('#page-home').innerHTML=`<div class="home-grid"><section class="card hero-card"><div><span class="eyebrow">Daily synthesis · v1 staging</span><h2>A focused day with a strong afternoon window.</h2><p>Your planner is prioritizing concentration, practical decisions, and reflection today. Treat the score as guidance—not certainty.</p><span class="window-chip">✦ Best window · 14:10–16:20</span></div><div class="score-ring"><div><strong>82</strong><span>alignment</span></div></div></section><section class="card planner-card"><div class="card-head"><div><span class="eyebrow">Timeline</span><h2>Your day</h2></div><button class="ghost-btn" id="inlineAdd">Add plan</button></div><div class="timeline" id="timeline">${taskList()}</div></section><section class="card insight-card"><span class="eyebrow">Why 82 today?</span><h3 style="margin-top:7px">Balanced signals, led by numerology</h3><div class="metric-row"><div class="metric"><strong>89</strong><span>Numerology</span></div><div class="metric"><strong>78</strong><span>Astrology</span></div><div class="metric"><strong>80</strong><span>Chinese zodiac</span></div></div><button class="ghost-btn" data-page="insights" style="margin-top:15px">See full reasoning →</button></section><section class="card reflection-card"><div class="card-head"><div><span class="eyebrow">Evening reflection</span><h3>Capture one line</h3></div><span class="save-state" id="reflectionState">Saved locally</span></div><textarea id="reflection" placeholder="What felt most aligned today?">${localStorage.getItem('cosmic.reflection')||''}</textarea></section></div>`;$('#inlineAdd')?.addEventListener('click',openModal);$('#reflection')?.addEventListener('input',e=>{localStorage.setItem('cosmic.reflection',e.target.value);$('#reflectionState').textContent='Saved'})}
function renderCalendar(){let first=new Date(2026,7,1).getDay();first=first===0?6:first-1;let cells='';for(let i=0;i<42;i++){let n=i-first+1;let d=new Date(2026,7,n);let inMonth=d.getMonth()===7;let score=60+((n*17)%35);let cls=score>=82?'high':score>=70?'mid':'low';let event=n===28?'2 plans':n===31?'Journal review':'';cells+=`<button class="day-cell ${!inMonth?'muted':''} ${n===28?'today':''}" data-day="${inMonth?n:''}" aria-label="${inMonth?`August ${n}, score ${score}`:'Adjacent month'}"><span class="day-number">${d.getDate()}</span>${inMonth?`<span class="luck-dot ${cls}"></span>`:''}${event?`<div class="day-event">${event}</div>`:''}</button>`}$('#page-calendar').innerHTML=`<div class="calendar-layout"><section class="card calendar-card"><div class="calendar-toolbar"><div><span class="eyebrow">Month view</span><h2 style="margin:5px 0 0">August 2026</h2></div><div class="month-nav"><button class="icon-btn" aria-label="Previous month">‹</button><button class="icon-btn" aria-label="Next month">›</button></div></div><div class="weekday-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div>${x}</div>`).join('')}</div><div class="month-grid">${cells}</div></section><aside class="card side-panel" id="datePanel"><span class="eyebrow">Selected date</span><h3 style="margin:6px 0 0">Friday, 28 August</h3><div class="day-score">82</div><span class="module-sub">Overall alignment</span><div class="breakdown"><div class="bar-row"><span>Numerology</span><div class="bar"><i style="width:89%"></i></div><b>89</b></div><div class="bar-row"><span>Astrology</span><div class="bar"><i style="width:78%"></i></div><b>78</b></div><div class="bar-row"><span>Chinese zodiac</span><div class="bar"><i style="width:80%"></i></div><b>80</b></div></div><div class="journal-prompt" style="margin-top:22px">Best for: focused work, reviewing plans, thoughtful conversations. Avoid treating any score as a guarantee for financial or life decisions.</div></aside></div>`;$$('.day-cell[data-day]').forEach(b=>b.addEventListener('click',()=>{if(!b.dataset.day)return;let n=+b.dataset.day,score=60+((n*17)%35);$('#datePanel').querySelector('h3').textContent=`August ${n}, 2026`;$('#datePanel').querySelector('.day-score').textContent=score}))}
function renderDiary(){let saved=localStorage.getItem('cosmic.diary')||'';let title=localStorage.getItem('cosmic.diaryTitle')||'A quieter, clearer day';let mood=localStorage.getItem('cosmic.mood')||'4';$('#page-diary').innerHTML=`<div class="diary-layout"><aside class="card entry-list"><div class="card-head"><div><span class="eyebrow">Entries</span><h3>Recent</h3></div></div><button class="entry-item active"><strong>Today</strong><span>28 Aug · ${saved?'Draft saved':'New entry'}</span></button><button class="entry-item"><strong>Yesterday</strong><span>27 Aug · Productive</span></button><button class="entry-item"><strong>Monday</strong><span>24 Aug · Reflective</span></button></aside><section class="card editor-card"><div class="card-head"><div><span class="eyebrow">Friday · 28 August</span></div><span class="save-state" id="diarySave">Saved locally</span></div><div class="journal-prompt">Reflection prompt · What decision felt easier today, and what information helped you make it?</div><input class="diary-title" id="diaryTitle" value="${escapeAttr(title)}" aria-label="Diary entry title"/><div class="mood-row" aria-label="Mood">${['1','2','3','4','5'].map((m,i)=>`<button class="mood ${m===mood?'selected':''}" data-mood="${m}" aria-label="Mood ${m}">${['😞','😕','😐','🙂','😊'][i]}</button>`).join('')}</div><textarea class="diary-editor" id="diaryEditor" placeholder="Write without pressure. This space is yours…">${escapeHtml(saved)}</textarea></section></div>`;function save(){localStorage.setItem('cosmic.diary',$('#diaryEditor').value);localStorage.setItem('cosmic.diaryTitle',$('#diaryTitle').value);$('#diarySave').textContent='Saved locally'}$('#diaryEditor').addEventListener('input',save);$('#diaryTitle').addEventListener('input',save);$$('.mood').forEach(b=>b.addEventListener('click',()=>{$$('.mood').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');localStorage.setItem('cosmic.mood',b.dataset.mood)}))}
function renderInsights(){const modules=[['Numerology','7','Personal day','Reflection & refinement','Today’s number favors review, analysis, and deliberate pacing. Use it to prioritize clarity over speed.','◌'],['Astrology','78','Transit score','Steady, introspective','The staging model frames today as supportive for concentration and thoughtful communication.','☾'],['Chinese Zodiac','80','Harmony score','Grounded momentum','A practical day for steady progress. Favor consistency over dramatic changes.','◇'],['Palmistry','—','Optional module','Image analysis not enabled','Palm analysis remains opt-in and will require a private image upload. No image is stored in this preview.','⌁']];$('#page-insights').innerHTML=`<div class="insights-grid">${modules.map(m=>`<section class="card insight-module"><div class="module-head"><div><span class="eyebrow">${m[0]}</span><h3 style="margin:6px 0 0">${m[3]}</h3></div><span class="module-icon">${m[5]}</span></div><div class="module-value">${m[1]}</div><div class="module-sub">${m[2]}</div><p class="module-copy">${m[4]}</p></section>`).join('')}</div><section class="card" style="padding:23px;margin-top:18px"><span class="eyebrow">Synthesis principle</span><h2 style="margin:7px 0 10px">One recommendation, with transparent reasoning.</h2><p class="module-copy" style="max-width:800px;margin:0">The production engine will keep each source score visible instead of hiding it behind a single mystical number. The app will clearly distinguish entertainment/self-reflection guidance from evidence-based advice and will never present luck scores as guarantees.</p></section>`}
function renderProfile(){ $('#page-profile').innerHTML=`<div class="profile-grid"><section class="card settings-card"><div class="card-head"><div><span class="eyebrow">Preferences</span><h2>Make it yours</h2></div></div><div class="settings-section"><h3>Daily rhythm</h3>${setting('Morning briefing','A concise planner + insight summary',true)}${setting('Evening reflection','A gentle diary prompt',true)}${setting('Lucky-time notifications','Notify only for high-confidence windows',true)}</div><div class="settings-section"><h3>Connections</h3>${setting('Calendar sync','Google / Apple connection',false)}${setting('Product analytics','Anonymous usage analytics',false)}</div><div class="settings-section"><h3>Privacy</h3>${setting('Palm image processing','Always opt-in per upload',false)}${setting('Personalized insights','Uses birth profile to calculate scores',true)}</div></section><aside class="card profile-summary"><div class="large-avatar">SB</div><span class="eyebrow">Staging profile</span><h2 style="margin:5px 0 8px">Preview workspace</h2><p>This review build intentionally uses local demo data. Production authentication and personal records will use the private Supabase schema already prepared.</p><div class="status-list"><div class="status-row"><span>Database</span><b class="status-good">Secured</b></div><div class="status-row"><span>Production deploy</span><b>Blocked by review</b></div><div class="status-row"><span>Payments</span><b>Not activated</b></div><div class="status-row"><span>Analytics</span><b>Not activated</b></div></div></aside></div>`;$$('.toggle').forEach(b=>b.addEventListener('click',()=>b.classList.toggle('on')))}
function setting(name,desc,on){return `<div class="settings-row"><span><strong>${name}</strong><small>${desc}</small></span><button class="toggle ${on?'on':''}" aria-label="Toggle ${name}"></button></div>`}
function escapeHtml(s=''){return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function escapeAttr(s=''){return escapeHtml(s).replace(/'/g,'&#39;')}
function openModal(){ $('#modalBackdrop').hidden=false;setTimeout(()=>$('#taskTitle').focus(),20)}function closeModal(){ $('#modalBackdrop').hidden=true;$('#taskForm').reset();$('#taskTime').value='14:30'}
$('#quickAdd').addEventListener('click',openModal);$('#closeModal').addEventListener('click',closeModal);$('#cancelTask').addEventListener('click',closeModal);$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});$$('[data-priority]').forEach(b=>b.addEventListener('click',()=>{$$('[data-priority]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.priority=b.dataset.priority}));$('#taskForm').addEventListener('submit',e=>{e.preventDefault();state.tasks.push({time:$('#taskTime').value,title:$('#taskTitle').value.trim(),category:$('#taskCategory').value,luck:84,status:'planned',priority:state.priority});localStorage.setItem('cosmic.tasks',JSON.stringify(state.tasks));renderHome();closeModal();toast('Plan added to your staging day')});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#searchBtn').addEventListener('click',()=>toast('Search is reserved for the connected-data build'));
renderHome();renderCalendar();renderDiary();renderInsights();renderProfile();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
